import { clamp } from "./adminUtils"

const now = Date.now()
const daysAgo = (d) => new Date(now - d * 24 * 60 * 60 * 1000).toISOString()

const tierMeta = {
  Tier1: { label: "Tier1", badge: "Tier1" },
  Tier2: { label: "Tier2", badge: "Tier2" },
  Tier3: { label: "Tier3", badge: "Tier3" },
}

function mkCandidate({
  id,
  name,
  college,
  collegeTier,
  district,
  isRural,
  isFirstGen,
  jobDensityIndex,
  cgpa,
  skills,
  projectsCount,
  internshipsCount,
  certificationsCount,
  experienceMonths,
  rawResumeText,
  processedAt,
  status = "under_review",
}) {
  return {
    id,
    name,
    college,
    collegeTier: tierMeta[collegeTier]?.badge ?? "Tier3",
    district,
    isRural: Boolean(isRural),
    isFirstGen: Boolean(isFirstGen),
    jobDensityIndex: clamp(jobDensityIndex ?? 50, 0, 100),
    resume: {
      cgpa: clamp(cgpa ?? 7.0, 0, 10),
      skills: skills ?? [],
      projectsCount: clamp(projectsCount ?? 0, 0, 12),
      internshipsCount: clamp(internshipsCount ?? 0, 0, 8),
      certificationsCount: clamp(certificationsCount ?? 0, 0, 12),
      experienceMonths: clamp(experienceMonths ?? 0, 0, 96),
      rawText: rawResumeText ?? "",
    },
    admin: {
      status,
      notes: "",
      lastActionAt: processedAt,
      lastActionBy: "admin_aj",
    },
    processedAt,
  }
}

export const ADMIN_MOCK_CANDIDATES = [
  mkCandidate({
    id: "HG-C-0001",
    name: "Priya Rajan",
    college: "Govt. Arts College, Ariyalur",
    collegeTier: "Tier3",
    district: "Ariyalur, TN",
    isRural: true,
    isFirstGen: true,
    jobDensityIndex: 22,
    cgpa: 8.1,
    skills: ["Python", "SQL", "Pandas", "ML Basics"],
    projectsCount: 4,
    internshipsCount: 1,
    certificationsCount: 2,
    experienceMonths: 8,
    rawResumeText: "Self-taught Python and SQL via offline resources. Built 4 projects (ETL, basic recommender, dashboard)...",
    processedAt: daysAgo(1),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0002",
    name: "Arjun Mehta",
    college: "IIT Bombay",
    collegeTier: "Tier1",
    district: "Mumbai, MH",
    isRural: false,
    isFirstGen: false,
    jobDensityIndex: 91,
    cgpa: 8.7,
    skills: ["React", "TypeScript", "Node.js", "AWS", "System Design"],
    projectsCount: 5,
    internshipsCount: 2,
    certificationsCount: 1,
    experienceMonths: 28,
    rawResumeText: "2+ years full-time SDE. Led feature delivery, AWS infra, TS monorepo...",
    processedAt: daysAgo(2),
    status: "shortlisted",
  }),
  mkCandidate({
    id: "HG-C-0003",
    name: "Kavya Suresh",
    college: "Gulbarga University",
    collegeTier: "Tier3",
    district: "Raichur, KA",
    isRural: true,
    isFirstGen: true,
    jobDensityIndex: 18,
    cgpa: 7.3,
    skills: ["Java", "SQL", "Spring Boot", "REST APIs"],
    projectsCount: 3,
    internshipsCount: 1,
    certificationsCount: 0,
    experienceMonths: 6,
    rawResumeText: "Backend internship. Built REST services, wrote SQL queries, basic caching and auth...",
    processedAt: daysAgo(3),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0004",
    name: "Rohan Kapoor",
    college: "Delhi University (SRCC)",
    collegeTier: "Tier2",
    district: "Delhi, DL",
    isRural: false,
    isFirstGen: false,
    jobDensityIndex: 88,
    cgpa: 7.9,
    skills: ["Analytics", "SQL", "Figma", "Product Sense"],
    projectsCount: 2,
    internshipsCount: 1,
    certificationsCount: 2,
    experienceMonths: 18,
    rawResumeText: "Product analyst. Built dashboards, ran experiments, stakeholder reporting...",
    processedAt: daysAgo(4),
    status: "flagged",
  }),
  mkCandidate({
    id: "HG-C-0005",
    name: "Meena Bai",
    college: "Jai Narain Vyas University",
    collegeTier: "Tier3",
    district: "Jaisalmer, RJ",
    isRural: true,
    isFirstGen: true,
    jobDensityIndex: 12,
    cgpa: 7.1,
    skills: ["HTML", "CSS", "JavaScript", "React Basics"],
    projectsCount: 5,
    internshipsCount: 0,
    certificationsCount: 1,
    experienceMonths: 0,
    rawResumeText: "Fresher. Built 5 small frontend projects, deployed on Netlify. Learned on mobile data...",
    processedAt: daysAgo(5),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0006",
    name: "Vikram Nair",
    college: "PSG College of Technology",
    collegeTier: "Tier2",
    district: "Coimbatore, TN",
    isRural: false,
    isFirstGen: false,
    jobDensityIndex: 62,
    cgpa: 8.0,
    skills: ["C++", "Embedded", "Python", "IoT"],
    projectsCount: 3,
    internshipsCount: 1,
    certificationsCount: 1,
    experienceMonths: 12,
    rawResumeText: "Embedded internship. IoT projects, C++ firmware, sensor integration...",
    processedAt: daysAgo(6),
    status: "rejected",
  }),
  mkCandidate({
    id: "HG-C-0007",
    name: "Sana Khan",
    college: "NIT Trichy",
    collegeTier: "Tier1",
    district: "Tiruchirappalli, TN",
    isRural: false,
    isFirstGen: true,
    jobDensityIndex: 55,
    cgpa: 9.2,
    skills: ["Python", "NLP", "PyTorch", "Docker"],
    projectsCount: 4,
    internshipsCount: 2,
    certificationsCount: 2,
    experienceMonths: 20,
    rawResumeText: "NLP internship, trained classifiers, deployed inference with Docker...",
    processedAt: daysAgo(0.3),
    status: "shortlisted",
  }),
  mkCandidate({
    id: "HG-C-0008",
    name: "Amit Borse",
    college: "Government Polytechnic, Nashik",
    collegeTier: "Tier3",
    district: "Nashik, MH",
    isRural: true,
    isFirstGen: false,
    jobDensityIndex: 34,
    cgpa: 6.8,
    skills: ["React", "Tailwind", "Firebase"],
    projectsCount: 6,
    internshipsCount: 0,
    certificationsCount: 1,
    experienceMonths: 4,
    rawResumeText: "Built a local services marketplace app for rural SMEs. Firebase auth + storage...",
    processedAt: daysAgo(7),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0009",
    name: "Nandini Iyer",
    college: "BITS Pilani",
    collegeTier: "Tier1",
    district: "Jaipur, RJ",
    isRural: false,
    isFirstGen: false,
    jobDensityIndex: 65,
    cgpa: 8.5,
    skills: ["Go", "Kubernetes", "SRE", "Linux"],
    projectsCount: 3,
    internshipsCount: 2,
    certificationsCount: 2,
    experienceMonths: 26,
    rawResumeText: "SRE internships, wrote Go services, CI/CD, k8s ops...",
    processedAt: daysAgo(8),
    status: "shortlisted",
  }),
  mkCandidate({
    id: "HG-C-0010",
    name: "Deepak Patil",
    college: "Shivaji University",
    collegeTier: "Tier2",
    district: "Kolhapur, MH",
    isRural: true,
    isFirstGen: true,
    jobDensityIndex: 29,
    cgpa: 7.6,
    skills: ["JavaScript", "Node.js", "MongoDB"],
    projectsCount: 4,
    internshipsCount: 1,
    certificationsCount: 0,
    experienceMonths: 10,
    rawResumeText: "Built Node APIs for small businesses. Worked part-time while studying...",
    processedAt: daysAgo(9),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0011",
    name: "Pooja Choudhary",
    college: "State Engineering College, Kota",
    collegeTier: "Tier2",
    district: "Kota, RJ",
    isRural: false,
    isFirstGen: true,
    jobDensityIndex: 41,
    cgpa: 8.3,
    skills: ["Java", "DSA", "Spring", "MySQL"],
    projectsCount: 2,
    internshipsCount: 1,
    certificationsCount: 1,
    experienceMonths: 14,
    rawResumeText: "Spring Boot APIs, MySQL schemas, DSA practice, coding contests...",
    processedAt: daysAgo(10),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0012",
    name: "Rahul Das",
    college: "Local College, Purulia",
    collegeTier: "Tier3",
    district: "Purulia, WB",
    isRural: true,
    isFirstGen: true,
    jobDensityIndex: 15,
    cgpa: 6.9,
    skills: ["Python", "Excel", "Power BI"],
    projectsCount: 3,
    internshipsCount: 0,
    certificationsCount: 2,
    experienceMonths: 2,
    rawResumeText: "Data reporting for NGOs. Built Power BI dashboards with limited connectivity...",
    processedAt: daysAgo(11),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0013",
    name: "Ishita Banerjee",
    college: "Jadavpur University",
    collegeTier: "Tier1",
    district: "Kolkata, WB",
    isRural: false,
    isFirstGen: false,
    jobDensityIndex: 70,
    cgpa: 8.9,
    skills: ["C++", "OS", "Networking", "Rust"],
    projectsCount: 2,
    internshipsCount: 2,
    certificationsCount: 0,
    experienceMonths: 24,
    rawResumeText: "Systems internships. Built a packet capture tool, OS scheduler project...",
    processedAt: daysAgo(12),
    status: "shortlisted",
  }),
  mkCandidate({
    id: "HG-C-0014",
    name: "Farhan Ali",
    college: "AMU",
    collegeTier: "Tier2",
    district: "Aligarh, UP",
    isRural: true,
    isFirstGen: false,
    jobDensityIndex: 27,
    cgpa: 7.2,
    skills: ["React", "Next.js", "Node.js"],
    projectsCount: 5,
    internshipsCount: 1,
    certificationsCount: 1,
    experienceMonths: 9,
    rawResumeText: "Built SSR apps, performance work, APIs. Worked remotely with patchy internet...",
    processedAt: daysAgo(13),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0015",
    name: "Lakshmi Devi",
    college: "Women’s College, Malkangiri",
    collegeTier: "Tier3",
    district: "Malkangiri, OD",
    isRural: true,
    isFirstGen: true,
    jobDensityIndex: 8,
    cgpa: 7.8,
    skills: ["Python", "Flask", "SQL"],
    projectsCount: 4,
    internshipsCount: 0,
    certificationsCount: 1,
    experienceMonths: 5,
    rawResumeText: "Built a simple job portal for local community. Offline-first design, Flask backend...",
    processedAt: daysAgo(14),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0016",
    name: "Karan Sharma",
    college: "IIT Delhi",
    collegeTier: "Tier1",
    district: "Delhi, DL",
    isRural: false,
    isFirstGen: false,
    jobDensityIndex: 88,
    cgpa: 8.4,
    skills: ["ML", "PyTorch", "Math", "MLOps"],
    projectsCount: 3,
    internshipsCount: 2,
    certificationsCount: 1,
    experienceMonths: 30,
    rawResumeText: "MLOps pipelines, model monitoring, Pytorch training. Strong coursework...",
    processedAt: daysAgo(15),
    status: "shortlisted",
  }),
  mkCandidate({
    id: "HG-C-0017",
    name: "Neha Saini",
    college: "Local College, Warangal",
    collegeTier: "Tier3",
    district: "Warangal, TG",
    isRural: false,
    isFirstGen: true,
    jobDensityIndex: 36,
    cgpa: 8.0,
    skills: ["UI/UX", "Figma", "Design Systems"],
    projectsCount: 6,
    internshipsCount: 1,
    certificationsCount: 3,
    experienceMonths: 10,
    rawResumeText: "Designed mobile-first UI kits for NGOs. Documented design systems in Figma...",
    processedAt: daysAgo(16),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0018",
    name: "Suresh Gopal",
    college: "NIT Surathkal",
    collegeTier: "Tier1",
    district: "Mangaluru, KA",
    isRural: false,
    isFirstGen: true,
    jobDensityIndex: 58,
    cgpa: 7.4,
    skills: ["Java", "Kafka", "Microservices"],
    projectsCount: 2,
    internshipsCount: 1,
    certificationsCount: 0,
    experienceMonths: 20,
    rawResumeText: "Built streaming services in internship, Kafka topics, consumer groups...",
    processedAt: daysAgo(17),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0019",
    name: "Ankita Mishra",
    college: "State University, Ranchi",
    collegeTier: "Tier2",
    district: "Ranchi, JH",
    isRural: true,
    isFirstGen: true,
    jobDensityIndex: 24,
    cgpa: 7.0,
    skills: ["Python", "Django", "PostgreSQL"],
    projectsCount: 3,
    internshipsCount: 0,
    certificationsCount: 1,
    experienceMonths: 7,
    rawResumeText: "Built Django apps. No formal internships; contributed to open source via cyber cafe...",
    processedAt: daysAgo(18),
    status: "under_review",
  }),
  mkCandidate({
    id: "HG-C-0020",
    name: "Aditya Kulkarni",
    college: "VIT Pune",
    collegeTier: "Tier2",
    district: "Pune, MH",
    isRural: false,
    isFirstGen: false,
    jobDensityIndex: 82,
    cgpa: 7.7,
    skills: ["React", "Node.js", "PostgreSQL", "Redis"],
    projectsCount: 4,
    internshipsCount: 1,
    certificationsCount: 1,
    experienceMonths: 16,
    rawResumeText: "Fullstack projects, caching, DB design. Internship at mid-size SaaS...",
    processedAt: daysAgo(19),
    status: "under_review",
  }),
]

